services:
  mlflow_server:
    build: .
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////app/mlflow.db
      - MLFLOW_ARTIFACT_URI=file:///app/mlruns
    restart: always

