# Dockerfile.api
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install dependencies for the API
RUN pip install --no-cache-dir -r requierements.txt

# Expose the port for the FastAPI application
EXPOSE 8000

# Command to start the FastAPI server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

